### ISSUE TITLE
explain how vcsh works

### ISSUE THREAD

**Issue by Dieterbe** [RichiH/vcsh#10]
as a new user, I wonder "do I need to do anything special to my git repositories in order to make them work with vcsh?"

the README says "vcsh will check if any file it would want to create exists", IMHO you should document how this works, how does vcsh differ from regular git? just by setting some env vars? when? when invoking `vcsh` ?

**Comment by alerque** [comment]
@Dieterbe, @supersym (aka @clojens), et all. I think I'm going to close this issue for now because I'm not exactly sure what if anything needs doing. The docs have improved quite a bit since 2011, and there are quite a few tutorials out there as well.

That being said I'm also sure there is lots that could still be improved or clarified. Like Richard I'm in the position of understanding Git really well and I have to step back sometimes and *work* at remembering that normal sane people aren't intimate with its internals. At this point I think we're past "how does this thing work?" (hence closing this issue), but I'm **quite open** to hearing specific questions or requests for clarification that we can work into the documentation. Where exactly are you getting stuck? What concept mentioned in the docs trips you up and could use a footnote?
