### ISSUE TITLE
Manage .gitattributes per repo

### ISSUE THREAD

**Issue by bricewge** [RichiH/vcsh#103]
Hi,

I would like to know if there is a way to manages .gitattributes per repo with vcsh. This would allow to use vcsh with AGWA/git-crypt which will be very useful for hiding personal informations.
If there isn't maybe using a .gitattributes.d like .gitignore.d would do the trick.

**Comment by nirvdrum** [comment]
This issue is currently the top hit on Google for "vcsh git-crypt". In case some one else comes across this issue, I just want to point you at #111, which changes the fix for this issue. While it's still supported, the default is now for vcsh to not manage gitattributes by default. You'll need to set the `VCSH_GITATTRIBUTES` env var to enable the functionality.
