### ISSUE TITLE
Avoid or warn about creating vcsh repo from bad mr url

### ISSUE THREAD

**Issue by tfnico** [RichiH/vcsh#122]
After I mr update a repo with a bad url repo within (foo.vcsh), I get an empy vcsh repo foo.

After I correct the url in foo.vcsh, the vcsh repo still has the wrong remote-url.

This caused me confusion a couple of times already. Is it possible to block vcsh creating a repo if the remote url is bad?

(RichiH: "should be doable")

**Comment by air** [comment]
I just got bitten by this. I'm a very tentative new user and had a malformed git URI of the form `ssh://git@your-git-server/vcsh/mr.git` from a tutorial. The vcsh behaviour was unexpected - rather than aborting, it created an empty repo.
Luckily I found this issue and learned that I should try a plain git command to verify the git URI.
