### ISSUE TITLE
vcsh $repo init breaks $repo

### ISSUE THREAD

**Issue by seveas** [RichiH/vcsh#186]
```
spirit:~$ vcsh init trash
Initialized empty shared Git repository in /home/dennis/.config/vcsh/repo.d/trash.git/
spirit:~$ vcsh trash init
Reinitialized existing shared Git repository in /home/dennis/.config/vcsh/repo.d/trash.git/
spirit:~$ vcsh trash status
warning: core.bare and core.worktree do not make sense
fatal: unable to set up work tree using invalid config
```

It looks like `git init` in a repo that _looks_ bare (has a foo.git name) sets core.bare to true. `vcsh trash config core.bare false` fixes the issue, but it would be nice if it didn't happen in the first place.

**Comment by RichiH** [comment]
Thanks for the report.

I have played with this several times now and I can't come up with a nice way to do this. It feels as if this is something we would need to bounce upstream. Do you know why `git init` might behave that way?

**Comment by RichiH** [comment]
I will take that as a no, then. :)

**Comment by alerque** [comment]
Based partly on my history with Git and a little bit of speculation, I would say this is Git's fault, not ours.

One of the early design decisions Git made was trying to combine various actions in umbrella commands that magically switched off their function based on context. This led to many detrimental edge cases over the years and upstream has acknowledged this was a mistake. Many newer commands are much more granular and some legacy ones have gotten phased out. However `git init` still has a split personality:

```console
$ man git init
NAME
       git-init - Create an empty Git repository or reinitialize an existing one
```

It's designed to **either** initialize a new repository or repair an existing one. In this case it's idea of a "repair" means restoring the repository to the way *it* would have initialized it and bulldozing any reason it might have gotten into another state.

I think the ultimate answer here is "don't do that".

We might be able to patch this up by extending `vcsh upgrade` to re-fix things like this that appear broken, but I worry we'd be making the same mistake Git did and break somebody's tweaked workflow because we thought we know better why something wasn't the way we expected it to be.
