### ISSUE TITLE
Request tag for recent release

### ISSUE THREAD

**Issue by abend** [RichiH/vcsh#221]
Hi.  I've created a vcsh package for the [pkgsrc](http://www.pkgsrc.org/) package build system so it can be made easily available on SmartOS and other platforms.  

It's easy to build from a version specified as a git tag, however the most recent seems to be v1.20151229.  If development is at a stable enough place, I'd like to request a new version tag be added so I can bump the version offered in pkgsrc.  

Let me know if there's anything I can do to help, and thanks for the excellent tool!

**Comment by alerque** [comment]
This would be useful for other package managers (like myself) too.

**Comment by alerque** [comment]
There was a nice round of up dates closing a lot of issues and pull requests a couple weeks back, but it looks like things are quiet at the moment. Now would be a great time to tag a release — after a number of cleanups but before any other upcoming stints of activity. Please!

**Comment by RichiH** [comment]
Aye. I am a few thousand kilometers away from my ssh keys ATM, but I will
release over the weekend.


Richard

Sent by mobile; excuse my brevity and the wall of text Gmail appends by
default.

On Sep 8, 2017 14:06, "Caleb Maclennan" <notifications@github.com> wrote:

There was a nice round of up dates closing a lot of issues and pull
requests a couple weeks back, but it looks like things are quiet at the
moment. Now would be a great time to tag a release — after a number of
cleanups but before any other upcoming stints of activity. Please!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/RichiH/vcsh/issues/221#issuecomment-328085702>, or mute
the thread

**Comment by ao2** [comment]
Hi, any news about a new tagged release?

In particular I am interested in the bash completion, I hope that would be in the Debian package too after a new upstream release. I can help with that if needed.

Thanks,
   Antonio

**Comment by alerque** [comment]
Please? With a cherry? :cherries: This was an issue in 2016, 2017, 2018, 2019, and is still an issue in 2020. @RichiH surely you are close to your SSH keys at least once a year ;-) I'd like to update [the Arch Linux package](https://aur.archlinux.org/packages/vcsh/) for this to something newer than 5 years old.

**Comment by alerque** [comment]
A few hours ago (thanks Richard) we cut a tag for [`v1.20190619`](https://github.com/RichiH/vcsh/releases/tag/v1.20190619), so this is taken care of.

v1.20190619 is a "safe harbor" release — the HEAD commit as it's been standing for a year and a half now. Since we're hoping to stir up some momentum again and will be making tweaks to the build and test system as well as reviewing what changes need to be made overall this release is something you can fall back on for the last known working state in case we break something on the `main` branch.

**Comment by lordkage** [comment]
It looks like the homebrew formula needs to be updated to get those of us that use brew
https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/vcsh.rb

**Comment by alerque** [comment]
@lordkage Homebrew relies on a "release" branch with some prebuilt artifacts. The last tag was a safe-harbor tag for people that were using Git HEAD to fall back on before we started merging a rash of changes. It was not a normal release cycle with prebulit parts. Since Homebrew is missing some related tooling the update will have to wait a little (unless you want to set it up). There is new release tooling to get the needed source artifacts is a form more distros can use easier coming up soon (see #288).

Whatever you are missing out on in 2+ years old anyway.

**Comment by RichiH** [comment]
@abend @ao2 @lordkage:
I just pushed v1.20190620 to https://github.com/RichiH/vcsh/tree/release : https://github.com/RichiH/vcsh/releases/tag/v1.20190620

That should ensure all downstream packaging automation picks up the safe harbour release.

Sorry for the wait; as you can see, there's upstream activity again :)

**Comment by RichiH** [comment]
And v1.20190621 because I failed to update the version hardcoded into `vcsh version`... This is the actual safe harbor now; sorry for all the noise.

**Comment by alerque** [comment]
Welcome to the VCS incarnation of the document naming problem :stuck_out_tongue:

![](https://imgs.xkcd.com/comics/documents_2x.png)
