### ISSUE TITLE
list-untracked does not respect .gitignore files

### ISSUE THREAD

**Issue by madduck** [RichiH/vcsh#267]
```
lotus:~/.gitignore.d% cat .gitignore
- *.bak
lotus:~/.gitignore.d% vcsh list-untracked -a
awesome.bak
[…]
```
Arguably, this should not happen, since a file that's being per-directory ignored from Git will almost never be considered a trackable file, and thus it makes no sense to include it in the output of untracked files.

**Comment by alerque** [comment]
Is this the same as #265?

**Comment by alerque** [comment]
After more review I don't think this the same as #265, but I also don't think it's valid. How this is handled will be determined by your setting for `$VCSH_GITIGNORE`. The default "exact" setting is very much there for a reason. Git isn't going to apply any local config files if it's being told that it's operating on a completely different repository, and I think this design is as it should be. If you use `vcsh write-gitignore` you should get a usable gitignore file for the repo.

I see what you mean about never wanting to track things like `*.bak` files, but I can easily thing of scenarios where the opposite would be true: I have gitignore files in several places that ignore things for normal Git purposes but have VCSH tracked files there as well. It's quite reasonable to have Git ignore a file but VCSH track it. Since you can't have it both ways I think the out of the box Git behavior is the best default. Anything else would be us kludging together our own ignore priority chain and that's not as easy as it sounds nor would we agree on what was correct.

If I'm missing something here please chime in again and I'll reevaluate.
