### ISSUE TITLE
TEST: Create test that tagged version is returned by `vcsh version`

### ISSUE THREAD

**Issue by RichiH** [RichiH/vcsh#41]
Else, I may/will forget to update this at some point in time.

**Comment by alerque** [comment]
Yup. Like with the current safe-harbor version tag ;-)

So....as written this is pretty hard to test for because by the time a test (at least remotely in CI) would fail the tag has already been created. A local check that verified this after tagging would do something. If you ran it. But I digress.

The real question I want to ask is how would you feel if I restructured this a bit to treat it as a *real* software project with a configure and build system instead of a "take it or leave it" script? My personal preference would be to just use autoconf / automake. I realize it's a bit long in the tooth, but it already handles a ton of things that even this project could benefit from. Off the top of my head a couple that come to mind:

* Move versioning to the configure system, optionally make it auto-generated based on the tag situation
* Local path discovery to things that may or may not be we have hard coded guesses.
* Man pages would be generated at tag time and automatically included in the source tarball on releases (made with `make dist`, automatically built and attached to tags on GitHub), `ronn` would only be required to build from Git, not from source packages.
* Build time dependency checks are better than run time failures.
* Easier on distro packagers. Right now packaging on Arch requires patching or goofy command invocations that you can only discover by parsing the Makefile. Configure flags are much more discoverable.

I realize there is an existing PR already dealing with many of the current Makefile ailments (most of which I agree with, yes I see you #167) but none of them go so far as actually introducing a configure step or making `vcsh` a generated script or doing any proper system discovery stuff.

Are there any systems currently supported by VCSH that have a POSIX shell plus `make` that **don't** have autoconf/automake? Would you consider distributing source packaging instead of flat `git archive` tarballs a bad thing (automated of course)?

Thoughts @RichiH?
